# ?????????????8080???????
server:
  port: 8080

# ????????????????????
spring:
  application:
    name: base-ai
  # DeepSeek????????OpenAI???????OpenAI????
  ai:
    openai:
      # DeepSeek?API????DeepSeek??????
      api-key: sk-8419e265472a4d45aefa7582ef21bb78
      # DeepSeek?API???????OpenAI?????????DeepSeek???
      base-url: https://api.deepseek.com
      # ????????
      chat:
        options:
          # ?????DeepSeek???deepseek-chat????????
          model: deepseek-chat
          # ????????0-1?0.7??????????????
          temperature: 0.7